### ISSUE TITLE
Can't compile because of "missing external type definition" ?

### ISSUE THREAD

**Issue by Shikanime** [bazelbuild/rules_typescript#331]
Hello,

I am migrating an Angular v7.1.0 project to Bazel using [github.com/alexeagle/angular-bazel-example](https://github.com/alexeagle/angular-bazel-example) as the main inspiration.

I still didn't successfully compile my application. The problem seem to be caused by a TypeScript  or/and Angular package BUILD but I have some problems with debugging it 😨

The application: 
[github.com/sfeir-open-source/xlayers/tree/build/bazel](https://github.com/sfeir-open-source/xlayers/tree/build/bazel)

@manekinekko

# Workspace

<details>
  <summary>Click to expand</summary>

```bazel
# The WORKSPACE file tells Bazel that this directory is a "workspace", which is like a project root.
# The content of this file specifies all the external dependencies Bazel needs to perform a build.

####################################
# ESModule imports (and TypeScript imports) can be absolute starting with the workspace name.
# The name of the workspace should match the npm package where we publish, so that these
# imports also make sense when referencing the published package.
workspace(name = "xlayers")

# The Bazel buildtools repo contains tools like the BUILD file formatter, buildifier
# This commit matches the version of buildifier in angular/ngcontainer
# If you change this, also check if it matches the version in the angular/ngcontainer
# version in /.circleci/config.yml
BAZEL_BUILDTOOLS_VERSION = "49a6c199e3fbf5d94534b2771868677d3f9c6de9"

http_archive(
    name = "com_github_bazelbuild_buildtools",
    url = "https://github.com/bazelbuild/buildtools/archive/%s.zip" % BAZEL_BUILDTOOLS_VERSION,
    strip_prefix = "buildtools-%s" % BAZEL_BUILDTOOLS_VERSION,
    sha256 = "edf39af5fc257521e4af4c40829fffe8fba6d0ebff9f4dd69a6f8f1223ae047b",
)

# The @angular repo contains rule for building Angular applications
http_archive(
    name = "angular",
    url = "https://github.com/angular/angular/archive/7.1.0.zip",
    strip_prefix = "angular-7.1.0",
)

# The @rxjs repo contains targets for building rxjs with bazel
http_archive(
    name = "rxjs",
    url = "https://registry.yarnpkg.com/rxjs/-/rxjs-6.3.3.tgz",
    strip_prefix = "package/src",
    sha256 = "72b0b4e517f43358f554c125e40e39f67688cd2738a8998b4a266981ed32f403",
)

# Angular material
# Using commit that is compatible with angular 7.0.4
# TODO(gmagolan): Update to https://github.com/angular/material2 v7.0.5 when released
http_archive(
    name = "angular_material",
    url = "https://github.com/DevVersion/material2/archive/c94e095841b063380b9d2c5611da1ff99445e516.zip",
    strip_prefix = "material2-c94e095841b063380b9d2c5611da1ff99445e516",
)

####################################
# Load and install our dependencies downloaded above.

load("@angular//packages/bazel:package.bzl", "rules_angular_dependencies")

rules_angular_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "check_bazel_version", "node_repositories", "yarn_install")

# The minimum bazel version to use with this example repo
# Bazel 0.19 supports the .bazelignore file
check_bazel_version("0.19.0")

node_repositories(
    node_version = "10.9.0",
    yarn_version = "1.12.1",
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()

# Browser test
load("@io_bazel_rules_webtesting//web:repositories.bzl", "browser_repositories", "web_test_repositories")

web_test_repositories()
browser_repositories(
    chromium = True,
    firefox = True,
)

# Load TypeScript
load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")

ts_setup_workspace()

# Setup Angular
load("@angular//:index.bzl", "ng_setup_workspace")

ng_setup_workspace()

load("@angular_material//:index.bzl", "angular_material_setup_workspace")

angular_material_setup_workspace()
```
</details>

# Build log

<details>
  <summary>Click to expand</summary>  

```bash
➜  lib git:(build/bazel) ✗ /opt/bazel/bazel build
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 1.237s, Critical Path: 0.01s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

</details>

# Run log

<details>
  <summary>Click to expand</summary>
  
```bash
➜  lib git:(build/bazel) ✗ bazel run //src:prodserver --verbose_failures
INFO: Build options have changed, discarding analysis cache.
yarn install v1.12.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @angular-devkit/build-webpack@0.10.6" has unmet peer dependency "webpack@^4.6.0".
warning " > @angular-devkit/build-webpack@0.10.6" has unmet peer dependency "webpack-dev-server@^3.1.4".
warning " > speed-measure-webpack-plugin@1.2.3" has unmet peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "@angular/bazel > tsickle@0.32.1" has incorrect peer dependency "typescript@>=2.4.2 <2.10".
warning "jest-preset-angular > ts-jest@23.1.4" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning "jest-preset-angular > ts-jest@23.1.4" has unmet peer dependency "babel-jest@^23.0.0 || ^24.0.0".
warning " > karma-mocha-reporter@2.2.5" has unmet peer dependency "karma@>=0.13".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 75.57s.
INFO: Analysed target //src:prodserver (214 packages loaded, 15700 targets configured).
INFO: Found 1 target...
WARNING: AngularTemplateCompile worker (id 6) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
WARNING: AngularTemplateCompile worker (id 7) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
WARNING: AngularTemplateCompile worker (id 4) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc
43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
WARNING: AngularTemplateCompile worker (id 5) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc
43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped.runfiles/xlayers/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
bazel-out/host/bin/external/angular/packages/bazel/src/ngc-wrapped/ngc-wrapped_bin.sh: 0f12602f950dacad3afd9dbdbf2f7c6092185dd6acef90eaa1ff3fbc43179726 -> a8ff5124bd2d01722301edcbe8536cba53d1b3351389115bfb2703a1910a8a13
WARNING: AngularTemplateCompile worker (id 9) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 5060
3665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/angular/@angular/bazel/ngc-wrapped: bfddf09996d7352c4aed0e586dd3
a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0
e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/xlayers/external/angular/@angular/bazel/ngc-wrapped: bfddf09996d
7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/xlayers/external/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39-> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
WARNING: AngularTemplateCompile worker (id 8) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 5060
3665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/angular/@angular/bazel/ngc-wrapped: bfddf09996d7352c4aed0e586dd3
a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/xlayers/external/angular/@angular/bazel/ngc-wrapped: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/xlayers/external/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39 -> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped_bin.sh: bfddf09996d7352c4aed0e586dd3a3ead89a6ef2b411f86fb93eef68db1cfe39-> 50603665ad8b71cfd7923a51323f69c0263b376e27a04243d5b13868b7240a25
ERROR: /Users/williamphetsinorath/Codes/sfeir-open-source/xlayers/src/app/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src/app:a
pp failed (Exit 1): ngc-wrapped failed: error executing command
(cd /private/var/tmp/_bazel_williamphetsinorath/ddc39d7215bcfeb4d52e41ea2c016537/execroot/xlayers && \
exec env - \
bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped '--node_options=--expose-gc' @@bazel-out/darwin-fastbuild/bin/src/app/app_tsconfig.json)
error TS2688: Cannot find type definition file for 'estree'.
error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'jasminewd2'.
error TS2688: Cannot find type definition file for 'jest'.
error TS2688: Cannot find type definition file for 'node'.
error TS2688: Cannot find type definition file for 'q'.
error TS2688: Cannot find type definition file for 'selenium-webdriver'.

Target //src:prodserver failed to build
INFO: Elapsed time: 155.599s, Critical Path: 47.05s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 18 processes: 18 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
</details>

**Comment by alexeagle** [comment]
First, just as FYI, your command `bazel build` did nothing because it found 0 targets. I filed https://github.com/bazelbuild/bazel/issues/6811 because I can understand why you'd expect that to do something.

For your error, I'd need to see the BUILD file, but I suspect you are using fine-grained dependencies and don't have `@npm//@types` in the `deps` of the failing target (that would prevent the TypeScript compiler from being able to find the files)
Another possibility is that the files are in the deps, but the tsconfig.json has `types: []` so the typescript compiler would not bother looking for typings files.

**Comment by manekinekko** [comment]
Thanks for the updates @alexeagle
@Shikanime can you try Alexe's suggestions and keep us in sync?

**Comment by Shikanime** [comment]
@alexeagle Thank for your quick reply.

Assuming that the file hierarchy of the project is a typical "ng new".

# ./tsconfig.json

There's my tsconfig file, I actually don't have any type fields.

<details>
  <summary>Click to expand</summary>

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@manekinekko/ngx-sketch-viewer": [
        "dist/manekinekko/ngx-sketch-viewer"
      ]
    }
  }
}
```
</details>

# ./src/tsconfig.app.json

This tsconfig is specifically extending for the previous tsconfig used for the applications part excluding test/spec.

<details>
  <summary>Click to expand</summary>

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": ["node"],
    "paths": {
      "@manekinekko/ngx-sketch-viewer": ["dist/manekinekko/ngx-sketch-viewer"]
    }
  },
  "exclude": ["src/test.ts", "**/*.spec.ts"]
}
```
</details>

# ./src/BUILD.bazel

For the src BUILD file i have almost the same as the example

<details>
  <summary>Click to expand</summary>

```bazel
package(default_visibility = ["//visibility:public"])

load("@angular//:index.bzl", "ng_module")
load("@build_bazel_rules_typescript//:defs.bzl", "ts_config", "ts_devserver")

ts_config(
    name = "tsconfig-spec",
    src = "tsconfig.spec.json",
    deps = [":tsconfig.json"],
)

ng_module(
    name = "src",
    srcs = glob(
        ["*.ts"],
        exclude = ["main.ts"],
    ),
    deps = [
        "//src/app",
        "@angular//packages/core",
        "@angular//packages/router",
    ],
)

ts_devserver(
    name = "devserver",
    additional_root_paths = [
        "npm/node_modules/zone.js/dist",
        "npm/node_modules/tslib",
        "npm/node_modules/@angular/material/prebuilt-themes",
    ],
    entry_module = "xlayers/src/main.dev",
    scripts = [
        ":require.config.js",
        ":module-id.js",
    ],
    # This is the URL we'll point our <script> tag at
    serving_path = "/bundle.min.js",
    static_files = [
        "@npm//node_modules/zone.js:dist/zone.min.js",
        "@npm//node_modules/tslib:tslib.js",
        "index.html",
    ],
    deps = ["//src"],
)

load("@build_bazel_rules_nodejs//:defs.bzl", "nodejs_binary", "rollup_bundle")

rollup_bundle(
    name = "bundle",
    additional_entry_points = [
        "src/app/home/home.module.ngfactory",
        "src/app/editor/editor.module.ngfactory",
    ],
    entry_point = "src/main.prod",
    deps = [
        "//src",
    ],
)

genrule(
    name = "copy_zonejs",
    srcs = ["@npm//node_modules/zone.js:dist/zone.min.js"],
    outs = ["zone.min.js"],
    cmd = "cp $< $@",
)

genrule(
    name = "copy_systemjs",
    srcs = ["@npm//node_modules/systemjs:dist/system.js"],
    outs = ["system.js"],
    cmd = "cp $< $@",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "history_server")

history_server(
    name = "prodserver",
    data = [
        "index.html",
        ":bundle",
        ":copy_systemjs",
        ":copy_zonejs",
    ],
)
```
</details>

# ./src/app/BUILD.bazel

And the BUILD file that I suspect caused the crash.

<details>
  <summary>Click to expand</summary>

```bazel
package(default_visibility = ["//visibility:public"])

load("@angular//:index.bzl", "ng_module")

ng_module(
    name = "app",
    srcs = [
        "app.component.ts",
        "app.module.ts",
    ],
    deps = [
        "//src/environments",
        "@angular//packages/core",
        "@angular//packages/common/http",
        "@angular//packages/platform-browser/animations",
        "@angular//packages/service-worker",
        "@angular//packages/platform-browser",
        "@angular//packages/router",
    ],
)
```

**Comment by Toxicable** [comment]
Just ran into this issue also
Dropping down to typescript 2.9.0 solves this issue for the time being.
for me it's 
```
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
```
even though I have this set 
```
    "lib": ["es2017", "es2016", "es2015", "dom", "esnext"],
```

**Comment by Shikanime** [comment]
But the BUILD root file of the Angular sample mentions that the attribute "tsconfig" can be omitted by using it:

```bazel
package(default_visibility = ["//visibility:public"])

alias(
    name = "tsconfig.json",
    actual = "//src:tsconfig.app.json",
)

**Comment by Toxicable** [comment]
@manekinekko In my case im trying to run a very simple nodejs script, no angular or any other libs.
This is our tsconfig (`"//:tsconfig.json"`)
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "esnext",
    "module": "commonjs",
    "typeRoots": ["node_modules/@types"],
    "types": ["node", "jasmine"],
    "paths": {
      "@workspace/*": ["libs/*"]
    }
  },
  "exclude": ["tmp", "dist", "bazel-out", "node_modules"],
  "bazelOptions": {
    "suppressTsconfigOverrideWarnings": false
  }
}
```
Since this works fine on 2.9.0 and is broken on > 3.0.0 I assume there must have been something that's changed there which needs updating in some config

**Comment by Toxicable** [comment]
I didn't re check ym rules_nodejs / rules_typescript versions, after updating those everything appears to be working again

**Comment by Shikanime** [comment]
I do think the @manekinekko issue is just because we imported a ts_library in a ng_module.

**Comment by Shikanime** [comment]
After a long road of failure, I unfortunately have a new typing problem.

I have a "sketch.typings.ts" file in the src folder that contains all types of declarations globally but I now have an inclusion problem. I don't know how to include this file globally.

```shell
➜  xlayers git:(build/bazel) ✗ bazel run //src:prodserver
INFO: Invocation ID: ec1ca120-bf0e-4678-bef4-178a207701c7
INFO: Analysed target //src:prodserver (1 packages loaded, 16 targets configured).
INFO: Found 1 target...
ERROR: /Users/shikanime/Codes/sfeir-open-source/xlayers/src/app/core/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src/app/core:core failed (Exit 1)
src/app/core/state/ui.state.ts(15,16): error TS2304: Cannot find name 'SketchData'.
src/app/core/state/ui.state.ts(16,17): error TS2304: Cannot find name 'SketchMSLayer'.
src/app/core/state/ui.state.ts(17,18): error TS2304: Cannot find name 'SketchMSLayer'.
src/app/core/state/ui.state.ts(18,19): error TS2304: Cannot find name 'SketchMSLayer'.
src/app/core/state/ui.state.ts(19,26): error TS2304: Cannot find name 'SketchMSPage'.
src/app/core/state/ui.state.ts(30,28): error TS2304: Cannot find name 'SketchData'.
src/app/core/state/ui.state.ts(39,29): error TS2304: Cannot find name 'SketchMSPage'.
src/app/core/state/ui.state.ts(44,28): error TS2304: Cannot find name 'SketchMSPage'.
src/app/core/state/ui.state.ts(49,29): error TS2304: Cannot find name 'SketchMSLayer'.
src/app/core/state/ui.state.ts(57,28): error TS2304: Cannot find name 'SketchMSLayer'.
src/app/core/state/page.state.ts(5,28): error TS2304: Cannot find name 'SketchMSPage'.
src/app/core/state/page.state.ts(8,8): error TS2304: Cannot find name 'SketchMSPage'.
src/app/core/state/page.state.ts(13,51): error TS2304: Cannot find name 'SketchMSPage'.

Target //src:prodserver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.837s, Critical Path: 4.33s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by Shikanime** [comment]
The issue was effectively due to missing `"@npm//@types/node"` and the "BUILD.bazel" at root project: 
```json
package(default_visibility = ["//visibility:public"])

alias(
    name = "tsconfig.json",
    actual = "//src:tsconfig.app.json",
)
```
actually works to omit the tsconfig attribute in each `ts_library' and `ng_module'.
