### ISSUE TITLE
Imports from `top_level/foo` work without the workspace

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#118]
The workspace name is a synonym for the npm package name. Non-relative imports should always start with the workspace.

We are doing the same migration internally at google.

**Comment by yohcop** [comment]
After upgrading from 0.7.0 (before this change) to 0.9.0, I see something strange: some imports still work without a namespace, some don't...

With the workspace set to `fz`, the following works. Note `Event` is imported without the workspace, from `event.type.d.ts`, and the others MUST be imported with `fz/` prefix. Could it be related to the fact that event.type is a .d.ts file, but not the other ones?
```
import { Event } from 'fitzenith/web/typings/event.type';
import { DistanceInputState, initialDistanceInput } from 'fz/fitzenith/web/app/utils/components/DistanceInput/state';
import { DurationInputState, initialDurationInput } from 'fz/fitzenith/web/app/utils/components/DurationInput/state';
```
Without the prefix, I do get errors like:
```
fitzenith/web/app/event-editor/editor/state.ts(3,58): error TS2307: Cannot find module 'fitzenith/web/app/utils/components/DurationInput/state'.
```
even though the dependency is declared correctly (and adding the workspace name to the import fixes things).
